# Generated by Django 3.1.5 on 2021-05-10 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210505_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAdresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, default='', max_length=120, verbose_name='Город')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='UsersContactPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=200, verbose_name='Номер')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='Связь по вотсу')),
                ('email_send', models.BooleanField(default=False, verbose_name='Связь по почте')),
                ('instagram', models.CharField(default='', max_length=100, verbose_name='Связь по инстаграмму')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Способ связи',
                'verbose_name_plural': 'Способы связи',
                'ordering': ('user',),
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
