# Generated by Django 3.1.5 on 2021-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210510_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscontactpreferences',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Связь по инстаграмму'),
        ),
    ]
