# Generated by Django 3.1.5 on 2021-05-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210510_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersadresses',
            old_name='address',
            new_name='adress',
        ),
    ]
