# Generated by Django 3.1.5 on 2021-05-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210510_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersadresses',
            name='adress',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='usersadresses',
            name='city',
            field=models.CharField(max_length=120, verbose_name='Город'),
        ),
    ]
