# Generated by Django 3.1.5 on 2021-05-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210511_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersadresses',
            name='default_adress',
            field=models.BooleanField(default=False, verbose_name='Адрес по умлочанию'),
        ),
    ]
