# Generated by Django 3.1.5 on 2021-05-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210511_2046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersadresses',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usersadresses',
            constraint=models.UniqueConstraint(fields=('user', 'default_adress'), name='default adress'),
        ),
    ]
