# Generated by Django 3.1.5 on 2021-05-11 17:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_auto_20210511_2049'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usersadresses',
            name='default adress',
        ),
        migrations.AlterUniqueTogether(
            name='usersadresses',
            unique_together={('user', 'default_adress')},
        ),
    ]
