# Generated by Django 3.1.5 on 2021-06-02 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoshop', '0004_auto_20210406_1730'),
        ('accounts', '0013_auto_20210513_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersadresses',
            options={'ordering': ('user', '-default_adress'), 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterField(
            model_name='userscontactpreferences',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Истаграм'),
        ),
        migrations.AlterField(
            model_name='userscontactpreferences',
            name='instagramm_send',
            field=models.BooleanField(default=False, verbose_name='Связь по инстаграму'),
        ),
        migrations.CreateModel(
            name='ChosenProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoshop.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
