# Generated by Django 3.1.5 on 2021-06-02 13:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0004_auto_20210406_1730'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_auto_20210602_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chosenproducts',
            options={'ordering': ('user',), 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные товары'},
        ),
        migrations.AlterUniqueTogether(
            name='chosenproducts',
            unique_together={('user', 'goods')},
        ),
    ]
