# Generated by Django 3.1.5 on 2021-06-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210602_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChosenProducts',
        ),
    ]
