# Generated by Django 3.1.5 on 2021-03-23 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=70, verbose_name='Категория')),
                ('category_info', models.TextField(blank=True, verbose_name='Иформация о каталоге')),
                ('category_image', models.ImageField(upload_to='images/categories', verbose_name='Изображение категории')),
                ('category_slug', models.SlugField(max_length=250, unique=True, unique_for_date='publish', verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=70, verbose_name='Имя товара')),
                ('goods_info', models.TextField(blank=True, verbose_name='Описание товара')),
                ('manufacturer', models.TextField(blank=True, verbose_name='Производитель товара')),
                ('product_care', models.TextField(blank=True, verbose_name='Уход')),
                ('goods_image', models.ImageField(upload_to='images/goods/%Y/%m', verbose_name='Изображение товара')),
                ('product_code', models.CharField(max_length=15, verbose_name='Код товара')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('exposed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Выставлен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('ожидается', 'Ожидается'), ('в наличии', 'В наличии'), ('под заказ', 'Под заказ'), ('нет в наличии', 'Нет в наличии')], default='ожидается', max_length=15, verbose_name='Статус')),
                ('goods_slug', models.SlugField(max_length=250, unique=True, unique_for_date='publish', verbose_name='Слаг')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_goods', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecoshop.category', verbose_name='Каталог')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-exposed',),
            },
        ),
    ]
