# Generated by Django 3.1.5 on 2021-03-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0002_auto_20210323_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=70, verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Слаг'),
        ),
    ]
